DROP TABLE USERDETAILS;
CREATE TABLE USERDETAILS (
         USERNAME varchar(40),
         NUMBER VARCHAR(20),
         EMAIL VARCHAR(100) ,  PRIMARY KEY (USERNAME) );

       INSERT INTO USERDETAILS (`USERNAME`, `NUMBER` , `EMAIL`) VALUES ('MAHESH', '9749578950' , 'mahesh.allagam@gmail.com');
       INSERT INTO USERDETAILS (`USERNAME`, `NUMBER`  , `EMAIL`) VALUES ('RAJESH', '00000000000' , 'rajesh.allagam@gmail.com');
